apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo-app-service
  name: mongo-app-service
  namespace: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mongo-app-service
  template:
    metadata:
      labels:
        name: mongo-app-service
    spec:
      imagePullSecrets:
      - name: dockerreposecret
      containers:
      - image: pachaanilkumar/mongo-app-service:39d940c
        name: mongo-app-service
        ports:
        - name: mongo-app-service
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-app-service
  name: mongo-app-service
  namespace: spring-boot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: mongo-app-service
