
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff-account-statement-service-web
  name: bff-account-statement-service-web
  namespace: boi-prelogin-profile-web-bff-dev
spec:
  selector:
    matchLabels:
      app: bff-account-statement-service-web
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: bff-account-statement-service-web
        maistra.io/expose-route: 'true'
    spec:
      containers:
      - args:
        - java -jar app.jar --spring.profiles.active=DEV
        command:
        - /bin/sh
        - -c
        env:
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-service.boi-shared-services-config-svc-mob-dev.svc.cluster.local:8080
        - name: SERVER_PORT
          value: '8080'
        - name: TZ
          value: Asia/Kolkata
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              key: username
              name: db-credentials
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              key: password
              name: db-credentials
        - name: MASKING_ENABLED
          value: 'true'
        - name: MASKING_FIELDS
          value: cookie,authToken,LtpaToken2,mobile,bankAccountNumber
        - name: CHAR_LENGTH
          value: '6'
        image: nprd-quay-quay-quay-enterprise.apps.nprd.ibm.local/ibmdev/bff-account-statement-service-web:67411ce
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10000
          timeoutSeconds: 10
        name: bff-account-statement-service-web
        ports:
        - containerPort: 8080
          name: bff-account-st
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        stdin: true
        tty: true
      restartPolicy: Always
