
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: bff-account-transforming-service-gateway
  namespace: boi-external-proxy-dev
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        protocol: HTTPS
        name: https
      tls:
        mode: SIMPLE
        credentialName: router-certs-default
      hosts:
        - bff-account-tr-boi-external-proxy-dev.apps.nprd.ibm.local
