
apiVersion: v1
kind: Service
metadata:
  name: bff-account-statement-service-web
  namespace: boi-prelogin-profile-web-bff-dev
  labels:
    app: bff-account-statement-service-web
spec:
  selector:
    app: bff-account-statement-service-web
  ports:
  - name: bff-account-st
    protocol: TCP
    appProtocol: http
    port: 8080
    targetPort: 8080
