
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bff-account-transforming-service-vs
  namespace: boi-external-proxy-dev
spec:
  gateways:
  - bff-account-transforming-service-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: bff-account-transforming-service
        port:
          number: 8080
