
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bff-account-statement-service-web-vs
  namespace: boi-prelogin-profile-web-bff-dev
spec:
  gateways:
  - bff-account-statement-service-web-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: bff-account-statement-service-web
        port:
          number: 8080
